/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.zimtools.zyod;

import org.junit.jupiter.api.Test;

class AppTest {
    private static final String YELLOW = "\u001B[35m";

    @Test
    void life() {
        System.out.println(YELLOW + "A Miracle was born!");
    }

}
